spec:
  destination:
    server: https://kubernetes.default.svc
traefik:
  version: 24.0.0
cert_manager:
  version: 1.13.1
  values:
    installCRDs: true
  webhook_domeneshop:
    version: c2fe09d
    values:
      groupName: taldev.no
      supportClusterIssuer: true
  issuers:
    acme:
      taldev_no:
        staging:
          name: taldevno-staging
          email: eirik@taldev.no
          server: https://acme-staging-v02.api.letsencrypt.org/directory
          secretName: letsencrypt-account-key-staging
          groupName: taldev.no
          credentials:
            secret: domeneshop-credentials
            api_token_ref: token
            api_secret_ref: secret
        prod:
          name: taldevno
          email: eirik@taldev.no
          server: https://acme-v02.api.letsencrypt.org/directory
          secretName: letsencrypt-account-key-staging
          groupName: taldev.no
          credentials:
            secret: domeneshop-credentials
            api_token_ref: token
            api_secret_ref: secret
argocd:
  ingress:
    host: "argocd.sbx.taldev.no"
    service_name: argo-cd-argocd-server
    port_name: http
    certificate: argocd-server-tls-certificate
    