apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cluster-infra
    server: {{ .Values.common.cluster }}
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: {{ .Values.metallb.version }}
  syncPolicy:
    automated: { }
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: basic-pool
  namespace: cluster-infra
spec:
  addresses:
    - {{ .Values.metallb.ip_range }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: cluster-infra