{{- if .Values.metallb.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: {{ .Values.common.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.common.namespace }}
    server: {{ .Values.common.cluster }}
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: {{ .Values.metallb.version }}
  syncPolicy:
    automated: { }
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: basic-pool
  namespace: {{ .Values.common.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  addresses:
    - {{ .Values.metallb.ip_range }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: {{ .Values.common.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
{{- end -}}