apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cluster-infra
    server: {{ .Values.common.cluster }}
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault-secrets-operator
      targetRevision: {{ .Values.vault-secrets-operator.version }}
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
