apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    server: {{ .Values.common.cluster }}
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: {{ .Values.traefik.version }}
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPAuth
metadata:
  name: hcp-auth-{{ .Values.vault_secrets_operator.hcp.app_name }}
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  organizationID: {{ .Values.vault_secrets_operator.hcp.organization_id }}
  projectID: {{ .Values.vault_secrets_operator.hcp.project_id }}
  servicePrincipal:
    secretRef: {{ .Values.vault_secrets_operator.hcp.secretRef }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: {{ .Values.vault_secrets_operator.hcp.app_name }}
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  appName: {{ .Values.vault_secrets_operator.hcp.app_name }}
  hcpAuthRef: hcp-auth-{{ .Values.vault_secrets_operator.hcp.app_name }}
  destination:
    create: true
    name: cluster-infra-core-secrets
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-certificate
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dnsNames:
    - "{{ .Values.argocd.ingress.host }}"
  issuerRef:
    name: "{{ .Values.cert_manager.issuers.acme.taldev_no.name }}"
    kind: ClusterIssuer
  secretName: "{{ .Values.argocd.ingress.certificate }}"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.argocd.ingress.host }}`)
      priority: 10
      services:
        - name: "{{ .Values.argocd.ingress.service_name }}"
          port: "{{ .Values.argocd.ingress.port_name }}"
    - kind: Rule
      match: Host(`{{ .Values.argocd.ingress.host }}`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: "{{ .Values.argocd.ingress.service_name }}"
          port: "{{ .Values.argocd.ingress.port_name }}"
          scheme: h2c
  tls:
    secretName: "{{ .Values.argocd.ingress.certificate }}"