apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-pod-test
  namespace: default
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sleep", "6000"]
      volumeMounts:
        - name: pvc
          mountPath: /mnt
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
  terminationGracePeriodSeconds: 1
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsUser: 65534
  volumes:
    - name: pvc
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: pvc-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: proxmox-data-ext4
            resources:
              requests:
                storage: 1Gi
