apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: basic-pool
  namespace: metallb-system
spec:
  addresses:
    - "10.0.69.250-10.0.69.251"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
