apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-ext4
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pvc
              mountPath: /mnt
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: nginx-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app.kubernetes.io/name: nginx
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: testpage-ingress-certificate
  namespace: default
spec:
  dnsNames:
    - "testpage.dev-tls-02.taldev.no"
  issuerRef:
    name: taldevno
    kind: ClusterIssuer
  secretName: testpage-ingress-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: testpage-ingress
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`testpage.dev-tls-02.taldev.no`)
      kind: Rule
      services:
        - name: nginx
          port: 80
  tls:
    secretName: testpage-ingress-tls
