apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-data-ext4
parameters:
  csi.storage.k8s.io/fstype: ext4
  storage: vm-storage
  cache: none
  ssd: "true"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
