[tool.poetry]
name = "homelab"
version = "0.1.0"
description = ""
authors = ["Eirik W. Talberg <eirik@taldev.no>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ansible = "^8.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
