#cloud-config

groups:
  - admingroup: [root,sys]
  - cloud-users
      'ssh_authorized_keys', 'ssh_redirect_user'.
users:
  - default
  - name: ${node_user}
    gecos: ${node_gecos}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /usr/bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${pubkey}

package_update: true
package_upgrade: true

packages:
  - fio

disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: true

fs_setup:
  - label: storage
    device: /dev/sdb1
    filesystem: "ext4"
    partition: "auto"

mounts:
  - [ sdb, /opt/data ]

runcmd:
  - hostnamectl hostname ${hostname}
  - chown ${node_user}:${node_user} /opt/data
  - shutdown -r now



