- name: "Upgrade all available packages"
  ansible.builtin.apt:
    upgrade: dist
  become: true
- name: "Check if reboot is necessary"
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
- debug:
    msg: "{{ reboot_required_file }}"
- name: "Reboot upgraded nodes"
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists
  become: true