kubeconfig: /home/{{ ansible_user }}/.kube/config
longhorn: true
cluster_name: sandbox
cluster_short_name: sbx
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
apps:
  cluster_infrastructure:
    targetRevision: HEAD
  argo_cd:
    chart_repo_url: https://argoproj.github.io/argo-helm
    chart_version: 5.46.8
  longhorn:
    chart_repo_url: https://charts.longhorn.io
    chart_version: 1.5.1