apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: stackgres
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
      chart: stackgres-operator
      targetRevision: 1.7.0
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: single-node
  namespace: stackgres
spec:
  instances: 1
  postgres:
    version: 'latest'
  pods:
    persistentVolume:
      size: '5Gi'