ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
kubeconfig: /home/{{ ansible_user }}/.kube/config
longhorn: true
cluster_name: prod
cluster_short_name: prod
cluster_tld: taldev.no
certbot_email: eirik@taldev.no
apps:
  cluster_infrastructure:
    targetRevision: cluster-infrastructure-v1.1.0
  argo_cd:
    chart_repo_url: https://argoproj.github.io/argo-helm
    chart_version: 5.46.8
  longhorn:
    chart_repo_url: https://charts.longhorn.io
    chart_version: 1.5.1