- name: "Secret: domeneshop-credentials - render template"
  ansible.builtin.template:
    src: templates/domeneshop-credentials.yaml.j2
    dest: "{{ manifest_directory }}/domeneshop-credentials.yaml"
- name: "Secret: domeneshop-credentials - apply"
  ansible.builtin.shell: "{{ kubectl_cmd }} apply -f {{ manifest_directory }}/domeneshop-credentials.yaml"