- set_fact:
    manifest_directory: /tmp/k8s
    kubectl_cmd: kubectl --kubeconfig {{ kubeconfig }}
- name: "Create manifest directory on host"
  ansible.builtin.file:
    dest: "{{ manifest_directory }}"
    state: directory
- ansible.builtin.shell: which helm
  register: helm_is_installed
  ignore_errors: true
- name: "Install Helm"
  ansible.builtin.import_tasks:
    file: install_helm.yaml
  when: helm_is_installed.stdout == ""
- name: "Configure ArgoCD"
  ansible.builtin.import_tasks:
    file: install_argo-cd.yaml
- name: "Configure Longhorn"
  ansible.builtin.import_tasks:
    file: install_longhorn.yaml
  when: longhorn
- name: "Configure Cluster secrets"
  ansible.builtin.import_tasks:
    file: cluster_secrets.yaml
- name: "Configure Cluster Infrastructure"
  ansible.builtin.import_tasks:
    file: install_cluster_infrastructure.yaml
- name: "Cleanup"
  ansible.builtin.file:
    dest: "{{ manifest_directory }}"
    state: absent


