- set_fact:
    manifest_directory: /tmp/k8s
    kubectl_cmd: kubectl --kubeconfig {{ kubeconfig }}
- name: "Create manifest directory on host"
  ansible.builtin.file:
    dest: "{{ manifest_directory }}"
    state: directory
- name: "Render Namespace template"
  ansible.builtin.template:
    src: templates/namespace.yaml.j2
    dest: "{{ manifest_directory }}/argocd-namespace.yaml"
- name: "Create ArgoCD namespace"
  ansible.builtin.command:
    cmd: "{{ kubectl_cmd }} apply -f {{ manifest_directory }}/argocd-namespace.yaml"
- name: "Render ArgoCD kustomization"
  ansible.builtin.template:
    src: templates/kustomization.yaml.j2
    dest: "{{ manifest_directory }}/kustomization.yaml"
- name: "Run kustomize"
  ansible.builtin.command:
    cmd: "{{ kubectl_cmd }} kustomize {{ manifest_directory }}"
- name: "Apply ArgoCD"
  ansible.builtin.command:
    cmd: "{{ kubectl_cmd }} apply -k {{ manifest_directory }}"
- name: "Render Application template"
  ansible.builtin.template:
    src: templates/application.yaml.j2
    dest: "{{ manifest_directory }}/application.yaml"
- name: "Apply Application manifest"
  ansible.builtin.command:
    cmd: "{{ kubectl_cmd }} apply -f {{ manifest_directory }}/application.yaml"
- name: "Cleanup"
  ansible.builtin.file:
    dest: "{{ manifest_directory }}"
    state: absent


