- name: Download and configure Ubuntu cloud image
  hosts:
    - ubuntu-dev
  run_once: true
  roles:
    - common
    - dev-ubuntu
    - ubuntu-cloud-image
  tasks:
    - ansible.builtin.fetch:
        src: "{{ cloud_image_location }}"
        dest: "{{ cloud_image_location }}"
        flat: yes
- name: "Upload cloud image"
  hosts:
    - "{{ pve_environment | default('pve-sbx') }}"
  run_once: true
  tasks:
    - ansible.builtin.copy:
        src: "{{ cloud_image_location }}"
        dest: "{{ cloud_image_location }}"
- name: Create PVE VM template
  hosts:
    - "{{ pve_environment | default('pve-sbx') }}"
  run_once: true
  roles:
    - pve-vm-template