- name: Download and configure Ubuntu cloud image
  hosts:
    - ws-01
  run_once: true
  roles:
    - ubuntu-cloud-image
- name: Copy image to PVE
  hosts:
    - localhost
  vars:
    image_from: "{{ hostvars['ws-01']['ansible_user'] }}@{{ hostvars['ws-01']['ansible_host'] }}:{{ cloud_image_location }}"
    image_to: "{{ hostvars['pve-01']['ansible_user'] }}@{{ hostvars['pve-01']['ansible_host'] }}:{{ cloud_image_location }}"
  tasks:
    - name: Copy image
      ansible.builtin.command:
        cmd: scp {{ image_from }} {{ image_to }}
- name: Create PVE VM template
  hosts:
    - pve-01
  run_once: true
  roles:
    - pve-vm-template