- name: Download kubeconfig from master
  hosts: master
  run_once: true
  tasks:
    - ansible.builtin.fetch:
        src: /home/{{ ansible_user }}/.kube/config
        dest: ~/.kube/config-k3s-{{ cluster_short_name }}.yaml
        flat: true