# This will probably get expanded with some state checking to allow it to run upgrades as well
- name: "Prepare for k3s install"
  hosts: k3s_cluster
  roles:
    - common
- name: "Install k3s on nodes"
  ansible.builtin.import_playbook: k3s-ansible/site.yml
- name: Download kubeconfig from master
  hosts: master
  run_once: true
  tasks:
    - ansible.builtin.fetch:
        src: /home/{{ ansible_user }}/.kube/config
        dest: ~/.kube/config-k3s-{{ cluster_short_name }}.yaml
        flat: true
