- name: "Provision nodes"
  hosts:
    - localhost
  vars:
    cluster_name: cluster_name
    token_secret_key: token_secret_key
  tasks:
    - debug:
        msg: "{{ token_secret_key }}"
    - name: "Create infrastructure"
      community.general.terraform:
        project_path: ../k8s/clusters/{{ cluster_name }}
        init_reconfigure: true
        force_init: true
        parallelism: 3
      environment:
        PM_API_TOKEN_SECRET: "{{ token_secret_key }}"