apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-certificate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  dnsNames:
    - "{{ .Values.argocd.ingress.host }}"
  issuerRef:
    name: "{{ .Values.cert_manager.issuers.acme.taldev_no.prod.name }}"
    kind: ClusterIssuer
  secretName: "{{ .Values.argocd.ingress.certificate }}"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.argocd.ingress.host }}`)
      priority: 10
      services:
        - name: "{{ .Values.argocd.ingress.service_name }}"
          port: "{{ .Values.argocd.ingress.port_name }}"
    - kind: Rule
      match: Host(`{{ .Values.argocd.ingress.host }}`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: "{{ .Values.argocd.ingress.service_name }}"
          port: "{{ .Values.argocd.ingress.port_name }}"
          scheme: h2c
  tls:
    secretName: "{{ .Values.argocd.ingress.certificate }}"