common:
  cluster: https://kubernetes.default.svc
vault_secrets_operator:
  version: v0.9.0
  hcp:
    organization_id: 3050c5b6-ddcf-43d3-b260-9555f249a40a
    project_id: 320c9a8d-83a9-4d69-8d6f-cc5174d8bf48
    secretRef: hcp-service-principal-credentials
    app_name: cluster-infra-core
metallb:
  enabled: true
  version: v0.14.8
  ip_range: 10.0.69.230-10.0.69.239
cert_manager:
  version: 1.16.1
  values:
    installCRDs: true
  webhook_domeneshop:
    version: c2fe09d
    values:
      groupName: taldev.no
      supportClusterIssuer: true
  issuers:
    acme:
      taldev_no:
        name: taldevno
        email: eirik@taldev.no
        server: https://acme-v02.api.letsencrypt.org/directory
        secretName: letsencrypt-account-key
        groupName: taldev.no
        credentials:
          secret: cluster-infra-core-secrets
          api_token_ref: domeneshop_token
          api_secret_ref: domeneshop_secret
